Feat/#13/submission detail
CodeMentor-CodingSite/CodeMentor-Front pull request #14
Opened 2024-01-22 06:00 UTC by EUNSUN23

## 1. 연관된 이슈 번호

- #13 

<br>

## 2. 작업 내용

### submissionDetail 페이지 퍼블리싱 
   #### 1. 코드블럭 생성위해 react-syntax-highlighter 패키지, @types/react-syntax-highlighter 패키지 추가 
      - c7ae2ef92fde229a5b39fed1303d1a506559fcd8, 239b99394493f4a7f11908d130b6e2224f34a1ea

   #### 2. submissionDetail페이지 퍼블리싱  
      - 982be0efe1c75f95c695a3648fea8e46a0fa7281, 7d9c89c6bbef6ffac97963790f6ee659d326ca3a, e08eb2d46556624d8f541e741c60c0705f47d208

<br>

## 3. 스크린샷 (선택사항)

### 라이트 모드 

![image](https://github.com/CodeMentor-CodingSite/CodeMentor-Front/assets/60612115/2dab3226-d022-4c44-91f8-bbb1dcdb250e)

### 다크 모드

![image](https://github.com/CodeMentor-CodingSite/CodeMentor-Front/assets/60612115/738b2448-67de-4307-b21c-6a983604ff21)

<br>

## 4. 추가사항 및 리뷰 요구사항 (선택사항)

이슈 생성시에는 이슈번호가 9번이었던것같은데... 왜 13번이 되었는지 모르겠네요 ㅜ 커밋 푸시한 뒤에 이슈번호 다른걸 알아서 커밋메세지 이슈번호는 수정 못했습니다.

2024-01-22 06:48 UTC, ijaesin requested changes
이슈 번호 할당하는거 헷갈리신거 같습니다
PR이 생성될 때도 각 PR이 이슈번호를 할당 받아서 이것까지 체크하고 만드셔야 해요

<img width="672" alt="Screenshot 2024-01-22 at 3 33 00 PM" src="https://github.com/CodeMentor-CodingSite/CodeMentor-Front/assets/80256934/58a27e40-8ea9-4939-ba1b-1f2033a74cfa">

위에 사진 보시면 제목 옆에 회색 글자로 #13 이라 되어있는게 실제 이슈번호에요.
그래서 'feat: #13 submission detail 페이지 퍼블리싱' 이슈번호는 13이고,
이 PR의 이슈번호는 14입니다.

2024-01-22 06:48 UTC, ijaesin commented on app/submissionDetail/page.tsx
> +                            href='/'
문제 풀이 페이지 url은 '/problems/[id]' 로 사용하고 있어요. 그리고 id는 문제 번호로 생각중입니다.

2024-01-22 07:08 UTC, EUNSUN23 commented
> 이슈 번호 할당하는거 헷갈리신거 같습니다 PR이 생성될 때도 각 PR이 이슈번호를 할당 받아서 이것까지 체크하고 만드셔야 해요
> 
> <img alt="Screenshot 2024-01-22 at 3 33 00 PM" width="672" src="https://private-user-images.githubusercontent.com/80256934/298484968-58a27e40-8ea9-4939-ba1b-1f2033a74cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDc1NTgsIm5iZiI6MTcwNTkwNzI1OCwicGF0aCI6Ii84MDI1NjkzNC8yOTg0ODQ5NjgtNThhMjdlNDAtOGVhOS00OTM5LWJhMWItMWYyMDMzYTc0Y2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA3MDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNjAyOWZiN2FhMzQzMTNlMDQ0YjcxZDk3MjIxYjAzY2E0MTYwNjg4NWYxZWJhNjJiYWViYjZlZjQyOWFmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y1BEWGFjpDKhq0xsp3puE0zrW4JIAlh1b4AyBZE_Qtc">
> 위에 사진 보시면 제목 옆에 회색 글자로 #13 이라 되어있는게 실제 이슈번호에요. 그래서 'feat: #13 submission detail 페이지 퍼블리싱' 이슈번호는 13이고, 이 PR의 이슈번호는 14입니다.

아 그렇군요.. pr까지 생각해야하는줄은 처음 알았어요. 감사합니다.

2024-01-22 07:19 UTC, ijaesin approved these changes
네 제목은 수정 가능하니까 실수하셔도 바로 고치시면 됩니다 !

LGTM

2024-01-22 07:28 UTC, EUNSUN23 commented
@ijaesin 

https://github.com/CodeMentor-CodingSite/CodeMentor-Front/pull/14#discussion_r1461407366 

이 부분 관련 상의드릴게 있어서요. 

리트코드 보니까,  edit 버튼 클릭하면 문제풀이 페이지에 사용자가 문제 푼 것 조회해서 보여주더라구요.

![image](https://github.com/CodeMentor-CodingSite/CodeMentor-Front/assets/60612115/e3b449fe-c5ae-4f31-bbb1-2b4bd3727e12)

뒤에 쿼리스트링으로 submittedId (아직 확정은 아니지만 제출 코드 index값) 같은 값을 보내야 할 것 같습니다. 그래서 문제 풀이 페이지에서 해당 쿼리스트링 존재하면 문제풀이 코드 조회해서 렌더링 해줘야 할 것 같아요.

2024-01-23 03:51 UTC, ijaesin commented
> @ijaesin
> 
> [#14 (comment)](https://github.com/CodeMentor-CodingSite/CodeMentor-Front/pull/14#discussion_r1461407366)
> 
> 넵 말씀하신 url로 수정하겠습니다. 추가적으로 상의 드릴게 있는데요.
> 
> 리트코드 보니까, edit 버튼 클릭하면 문제풀이 페이지에 사용자가 문제 푼 것 조회해서 보여주더라구요.
> 
> ![image](https://private-user-images.githubusercontent.com/60612115/298497559-e3b449fe-c5ae-4f31-bbb1-2b4bd3727e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODE5NDIsIm5iZiI6MTcwNTk4MTY0MiwicGF0aCI6Ii82MDYxMjExNS8yOTg0OTc1NTktZTNiNDQ5ZmUtYzVhZS00ZjMxLWJiYjEtMmI0YmQzNzI3ZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAzNDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMTBmZDU5N2E5OTliMGM4N2YwZTQ3MGJjMjdhY2I4MmI3MzA0MWE2YjhlODU1MzJlMDU3ZDhjNDU3MTc4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xj37ayp6rVMZDdzrbS_mRUjeBKniPFjQK0_FSvstUv4)
> 
> 뒤에 쿼리스트링으로 submittedId (아직 확정은 아니지만 제출 코드 index값) 같은 값을 보내야 할 것 같습니다. 그래서 문제 풀이 페이지에서 해당 쿼리스트링 존재하면 문제풀이 코드 조회해서 렌더링 해줘야 할 것 같아요.

리트코드나 다른 코딩 사이트보니, 풀었던 문제들은 url 변경 없이 마지막 제출 코드가 남아있는 걸로 나오네요.
은선님 말씀대로 쿼리스트링으로 넘기는 방법도 좋아 보입니다.

2024-01-23 07:24 UTC, merged